version: '3'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: transbandung-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - transbandung-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # User Management Service
  user-service:
    build: ./user-service
    container_name: transbandung-user-service
    ports:
      - "4001:4000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=transbandung_user
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - transbandung-network

  # Booking Service
  booking-service:
    build: ./booking-service
    container_name: transbandung-booking-service
    ports:
      - "4002:4000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=transbandung_booking
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - transbandung-network

  # Route Schedule Service
  route-service:
    build: ./route-service
    container_name: transbandung-route-service
    ports:
      - "4003:4000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=transbandung_route
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - transbandung-network

  # Review Rating Service
  review-service:
    build: ./review-service
    container_name: transbandung-review-service
    ports:
      - "4004:4000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=transbandung_review
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - transbandung-network

  # Payment Service
  payment-service:
    build: ./payment-service
    container_name: transbandung-payment-service
    ports:
      - "4005:4000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=transbandung_payment
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - transbandung-network

  # API Gateway with GraphQL
  api-gateway:
    build: ./api-gateway
    container_name: transbandung-api-gateway
    ports:
      - "4000:4000"
    environment:
      - USER_SERVICE_URL=http://user-service:4000/graphql
      - BOOKING_SERVICE_URL=http://booking-service:4000/graphql
      - ROUTE_SERVICE_URL=http://route-service:4000/graphql
      - REVIEW_SERVICE_URL=http://review-service:4000/graphql
      - PAYMENT_SERVICE_URL=http://payment-service:4000/graphql
    depends_on:
      - user-service
      - booking-service
      - route-service
      - review-service
      - payment-service
    networks:
      - transbandung-network

  # Frontend Service
  frontend:
    build: ./frontend
    container_name: transbandung-frontend
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - API_GATEWAY_URL=http://api-gateway:4000/graphql
    depends_on:
      api-gateway:
        condition: service_started
    networks:
      - transbandung-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  transbandung-network:
    driver: bridge

volumes:
  mysql-data:
